services:
  postgres:
    image: postgres:16
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    networks:
      - keycloak
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped 